match_records:
  description: |
    Use simple_dividend_csv tool to read both CSV files:
    - data/NBIM_Dividend_Bookings 1.csv
    - data/CUSTODY_Dividend_Bookings 1.csv
    
    CRITICAL: For events with multiple records (same COAC_EVENT_KEY), aggregate them:
    
    For each unique COAC_EVENT_KEY:
    1. Sum NBIM amounts by currency: GROSS_AMOUNT_QUOTATION, NET_AMOUNT_QUOTATION, WTHTAX_COST_QUOTATION
    2. Sum NBIM shares: NOMINAL_BASIS (total across all records for this event)
    3. Sum Custody amounts by original currency: GROSS_AMOUNT, NET_AMOUNT_QC, TAX  
    4. Sum Custody shares: NOMINAL_BASIS (total across all records)
    5. Extract rates: WTHTAX_RATE (NBIM) vs TAX_RATE (Custody)
    6. Note securities lending: LOAN_QUANTITY, HOLDING_QUANTITY, LENDING_PERCENTAGE
    
    Output format: 
    "[Event Key] Company: [Name]
    NBIM Totals: Gross=[Amount Currency], Net=[Amount Currency], Tax=[Amount Currency], Shares=[Total]
    Custody Totals: Gross=[Amount Currency], Net=[Amount Currency], Tax=[Amount Currency], Shares=[Total]
    Lending: [LOAN_QUANTITY] on loan of [HOLDING_QUANTITY] total ([LENDING_PERCENTAGE]%)"
  expected_output: "Properly aggregated data for each unique event with currency consistency"
  agent: data_detective

calculate_differences:
  description: |
    CRITICAL: Convert amounts to common currency before comparison when currencies differ.
    
    Using aggregated data from previous task, for each COAC_EVENT_KEY:
    
    1. Check if currencies match between NBIM and Custody totals
    2. If currencies match, calculate differences directly:
       - Gross: Custody Total - NBIM Total = difference
       - Net: Custody Total - NBIM Total = difference  
       - Tax: Custody Total - NBIM Total = difference
       - Percentage: (difference ÷ NBIM amount) × 100
    3. If currencies don't match, convert to common currency using available FX rates:
       - Use NBIM FX rate or Custody FX rate (whichever available)
       - Convert NBIM amounts to USD or Custody amounts to local currency
       - Then calculate differences as above
       - Note which FX rate was used for transparency
    4. Only flag as "CURRENCY MISMATCH" if no FX rate available for conversion
    
    Output format: 
    "[Event] Currency: [CCY] (converted using [rate source] FX rate: [rate])
    Gross: Custody [Amount] - NBIM [Amount] = [+/-Difference] ([Y%])
    Net: Custody [Amount] - NBIM [Amount] = [+/-Difference] ([Y%]) 
    Tax: Custody [Amount] - NBIM [Amount] = [+/-Difference] ([Y%])"
  expected_output: "Currency-consistent calculations with clear difference identification"
  agent: math_calculator

validate_positions:
  description: |
    Compare share quantities and validate securities lending accounting:
    
    For each COAC_EVENT_KEY:
    1. Compare total positions: NBIM NOMINAL_BASIS vs Custody (HOLDING_QUANTITY + LOAN_QUANTITY)
    2. Validate lending math: Does HOLDING_QUANTITY + LOAN_QUANTITY = total position?
    3. Calculate dividend-receiving shares: HOLDING_QUANTITY (shares actually held)
    4. Only flag as CRITICAL if total positions don't match after accounting for lending
    
    CRITICAL UNDERSTANDING: Securities lending means:
    - HOLDING_QUANTITY = shares physically held (receive dividends)
    - LOAN_QUANTITY = shares lent out (borrower receives dividends)
    - TOTAL = HOLDING_QUANTITY + LOAN_QUANTITY should match NBIM NOMINAL_BASIS
    
    Output format: 
    "[Event] Position Validation:
    - NBIM Total: [NOMINAL_BASIS] shares
    - Custody Total: [HOLDING_QUANTITY] held + [LOAN_QUANTITY] on loan = [sum] total
    - Status: MATCH/CRITICAL MISMATCH
    - Lending Impact: [LOAN_QUANTITY] shares ([%]) not receiving beneficial dividend treatment"
  expected_output: "Comprehensive position analysis including lending impact on dividend entitlement"
  agent: position_validator

analyze_tax_rates:
  description: |
    Compare tax rates and identify treaty optimization opportunities:
    
    For each event:
    1. Extract tax rates: NBIM WTHTAX_RATE vs Custody TAX_RATE
    2. Calculate financial impact of rate differences on total dividend
    3. Flag differences >1% as potential treaty opportunities
    4. Identify which system achieves better tax treatment
    5. Assess if NBIM could benefit from custody's approach
    
    Output format: "[Event] Tax Analysis:
    - NBIM Rate: X% vs Custody Rate: Y% (difference: Z%)
    - Financial Impact: [amount] extra tax paid by higher rate system
    - Treaty Opportunity: [YES/NO] - [explanation]
    - Recommendation: [action to optimize tax treatment]"
  expected_output: "Tax rate comparison identifying potential treaty issues or rate errors"
  agent: tax_analyst

check_securities_lending:
  description: |
    Analyze securities lending impact on dividend tax efficiency:
    
    For each event with lending (LOAN_QUANTITY > 0):
    1. Calculate lending impact: LOAN_QUANTITY / HOLDING_QUANTITY = lending %  
    2. Determine shares receiving beneficial tax treatment: HOLDING_QUANTITY - LOAN_QUANTITY
    3. Calculate tax loss: Lending % × Total Dividend × (Standard Rate - Treaty Rate)
    4. Assess if lending destroys tax efficiency
    
    For events with no lending:
    - Report "No lending detected - full tax treaty benefits available"
    
    Output format:
    "[Event] Lending Analysis:
    - Shares on loan: [LOAN_QUANTITY] of [HOLDING_QUANTITY] ([X%])
    - Shares with treaty benefits: [HOLDING_QUANTITY - LOAN_QUANTITY] ([effective %])
    - Tax efficiency impact: [HIGH/MEDIUM/LOW] - [explanation]
    - Estimated tax cost of lending: [calculation if possible]"
  expected_output: "Detailed lending impact on tax efficiency and dividend entitlement"
  agent: securities_lending_checker

validate_fx_rates:
  description: |
    Validate FX rates and currency conversion consistency:
    
    For each event, check currency handling:
    1. Single currency events (USD/USD, CHF/CHF): Verify no FX conversion needed
    2. Multi-currency events: Extract and compare FX rates from both systems
    3. Cross-currency settlements: Validate conversion accuracy
    4. Flag significant rate differences that could indicate unfavorable pricing
    
    Output format:
    "[Event] FX Analysis:
    - Currency pair: [NBIM currency] to [Settlement currency]  
    - NBIM rate: [rate if applicable]
    - Custody rate: [rate if applicable]
    - Rate difference: [X%] - [ACCEPTABLE/EXCESSIVE] 
    - Currency consistency: [OK/ISSUES DETECTED]"
  expected_output: "Comprehensive FX validation with currency conversion analysis"
  agent: fx_validator

assess_risk:
  description: |
    Prioritize findings using multiple risk factors:
    
    For each event, evaluate ALL risk factors:
    1. Financial impact: Amount differences and percentages
    2. Position mismatches: Share quantity differences (CRITICAL - invalidates all calculations)
    3. Securities lending: Tax efficiency destruction
    4. Currency issues: FX rate problems or currency mismatches
    5. Tax optimization: Missed treaty opportunities
    
    Priority assignment (use HIGHEST applicable):
    - CRITICAL: TRUE position mismatches after accounting for securities lending, currency comparison errors
    - HIGH: >$100,000 differences, >5% differences, tax rate differences >2%, significant lending impact
    - MEDIUM: $10,000-$100,000 differences, 2-5% differences, tax rate differences 1-2%
    - LOW: <$10,000 differences, <2% differences, minor lending activity
    - PERFECT: No differences and no issues detected
    
    IMPORTANT: Securities lending where HOLDING_QUANTITY + LOAN_QUANTITY = NBIM total is NOT a position mismatch
    
    Output format: 
    "[Event] Priority: [LEVEL] - Drivers: [list key issues]
    Financial: [largest amount/% difference]
    Operational: [position/lending/FX issues]
    Action required: [immediate/planned/monitoring]"
  expected_output: "Comprehensive risk assessment considering all factors including lending and positions"
  agent: risk_prioritizer

write_report:
  description: |
    Create a comprehensive executive report using ALL previous agent outputs.
    
    Extract and use the ACTUAL data from all previous task results.
    
    REQUIRED STRUCTURE:
    
    EXECUTIVE SUMMARY:
    - Total events processed: [COUNT from previous results]
    - Events by status: [COUNT PERFECT vs COUNT with breaks]
    - Priority breakdown: [PERFECT: X, HIGH: Y, MEDIUM: Z, LOW: W from risk assessment]
    
    DETAILED FINDINGS:
    For EACH event found in previous results, extract actual data:
    [Event ID] Company: [Company name from data matching results]
    - Gross Amount: NBIM [amount] vs Custody [amount] = [difference] ([percentage]%)
    - Net Amount: NBIM [amount] vs Custody [amount] = [difference] ([percentage]%)  
    - Tax Amount: NBIM [amount] vs Custody [amount] = [difference] ([percentage]%)
    - Position Status: NBIM [shares] vs Custody [shares] - [MATCH/MISMATCH]
    - Securities Lending: [loan quantity] shares ([percentage]%) on loan
    - Tax Rates: NBIM [rate]% vs Custody [rate]% (difference: [diff]%)
    - Priority: [level from risk assessment] - [specific reasons from risk assessment]
    
    FINANCIAL IMPACT SUMMARY:
    - Total value of discrepancies: [calculate sum from all differences found]
    - Largest single discrepancy: [identify from differences calculated]
    - Tax optimization opportunities: [extract from tax analysis results]
    
    ACTIONABLE RECOMMENDATIONS:
    HIGH PRIORITY ACTIONS:
    - [Extract specific recommendations from risk assessment for HIGH priority events]
    MEDIUM PRIORITY ACTIONS:
    - [Extract specific recommendations from risk assessment for MEDIUM priority events]
    
    Parse the previous agent outputs to extract all actual data, amounts, company names, and recommendations.
  expected_output: "Comprehensive report with specific metrics extracted from all previous agent findings"
  agent: report_writer