match_records:
  description: |
    IMPORTANT: You have access to raw CSV data through the crew inputs.
    The CSV data is available as: {nbim_csv_data} and {custody_csv_data}
    
    Parse the raw CSV data to match dividend records between NBIM and Custody systems.
    
    FIRST: Confirm you can access the CSV data by showing the first few lines of each file.
    THEN: Parse the full datasets.
    
    YOUR TASK:
    1. Parse both CSV files manually (they use semicolon ; as delimiter)
    2. Extract headers and data rows from each file
    3. Group NBIM records by COAC_EVENT_KEY (preserve individual accounts)
    4. Group Custody records by COAC_EVENT_KEY (preserve individual accounts)
    5. For events with multiple rows - PRESERVE ACCOUNT-LEVEL DETAIL:
       - List each account separately with its amounts and currencies
       - Calculate totals but show individual account breakdowns
       - Identify which specific accounts have discrepancies
    6. Match events between NBIM and Custody using COAC_EVENT_KEY
    
    CRITICAL: PRESERVE ORIGINAL CURRENCIES - DO NOT CONVERT TO USD
    
    Output format for each event (multi-account example):
    "[Event Key] Company: [ORGANISATION_NAME] - Currency: [QUOTATION_CURRENCY]
    
    NBIM ACCOUNTS:
    - Account [row#]: Gross=[GROSS_AMOUNT_QUOTATION] [currency], Net=[NET_AMOUNT_QUOTATION] [currency], Shares=[NOMINAL_BASIS]
    - NBIM TOTAL: Gross=[sum] [currency], Net=[sum] [currency], Tax=[sum of WTHTAX_COST_QUOTATION] [currency], Shares=[sum]
    
    CUSTODY ACCOUNTS:  
    - Account [CUSTODY]: Gross=[GROSS_AMOUNT] [currency], Net=[NET_AMOUNT_QC] [currency], Shares=[NOMINAL_BASIS], Lending=[LOAN_QUANTITY]
    - CUSTODY TOTAL: Gross=[sum] [currency], Net=[sum] [currency], Tax=[sum of TAX] [currency], Shares=[sum], Total Lending=[sum of LOAN_QUANTITY]
    
    CURRENCY INFO:
    - NBIM: [QUOTATION_CURRENCY] → [SETTLEMENT_CURRENCY] (FX Rate: [AVG_FX_RATE_QUOTATION_TO_PORTFOLIO])
    - Custody: [CURRENCIES] → [SETTLED_CURRENCY] (FX Rate: [FX_RATE])
    - Cross-currency: [IS_CROSS_CURRENCY_REVERSAL]
    
    DATES:
    - NBIM Ex Date: [EXDATE], Payment Date: [PAYMENT_DATE]
    - Custody Ex Date: [EVENT_EX_DATE], Event Payment Date: [EVENT_PAYMENT_DATE], Actual Pay Date: [PAY_DATE]
    - Payment Processing Delay: [PAY_DATE - EVENT_PAYMENT_DATE in days] days
    - Delay Analysis: [If delay >0, note if due to international security or currency conversion (IS_CROSS_CURRENCY_REVERSAL)]"
    
    IMPORTANT: Parse CSV manually, maintain account-level granularity, preserve currencies.
  expected_output: "Account-level structured data parsed directly from raw CSV with original currencies preserved"
  agent: data_detective

calculate_differences:
  description: |
    Using the parsed account-level data from the previous task, calculate precise amount differences.
    
    CRITICAL: Work in ORIGINAL CURRENCIES - do not convert to USD prematurely.
    
    For each event that was matched:
    1. Calculate differences between NBIM and Custody TOTAL amounts (preserve currency)
    2. Calculate percentage differences using original amounts
    3. For multi-account events, identify which specific accounts have discrepancies
    4. Handle currency-specific calculations properly
    
    Currency-Aware Calculations:
    - Same currency events: Direct subtraction (CHF - CHF, USD - USD)
    - Cross-currency events: Note currency difference, calculate in both currencies
    - Multi-currency: Show settlement currency amounts for comparison
    
    Account-Level Analysis (for multi-account events like Nestle):
    - Compare each NBIM account vs corresponding Custody account
    - Identify specific accounts with mismatches
    - Calculate per-account differences before totaling
    
    Enhanced Output Format:
    "[Event Key] Company: [company name] - Base Currency: [currency]
    
    ACCOUNT-LEVEL DIFFERENCES (if multi-account):
    - Account [ID]: NBIM [amount] [currency] vs Custody [amount] [currency] = [diff] [currency]
    
    TOTAL DIFFERENCES:
    - Gross: NBIM [total] [currency] vs Custody [total] [currency] = [difference] [currency] ([percentage]%)
    - Net: NBIM [total] [currency] vs Custody [total] [currency] = [difference] [currency] ([percentage]%)  
    - Tax: NBIM [total] [currency] vs Custody [total] [currency] = [difference] [currency] ([percentage]%)
    - Position: NBIM [shares] vs Custody [shares] = [difference] shares
    
    CURRENCY ANALYSIS:
    - NBIM Currency: [QUOTATION_CURRENCY] → [SETTLEMENT_CURRENCY]
    - Custody Currency: [CURRENCIES] → [SETTLED_CURRENCY]  
    - Settlement Amounts: NBIM [settlement_amount] vs Custody [settlement_amount] = [diff] (if different currencies)
    
    SIGNIFICANCE: [CRITICAL/HIGH/MEDIUM/LOW based on amounts and percentages]"
    
    Significance Thresholds:
    - CRITICAL: Position differences or >10% amount differences
    - HIGH: >5% differences or significant absolute amounts
    - MEDIUM: 2-5% differences or moderate absolute amounts  
    - LOW: <2% differences and minimal absolute amounts
  expected_output: "Precise currency-aware amount differences with account-level detail"
  agent: math_calculator

validate_positions:
  description: |
    Validate share positions using the parsed data from previous tasks.
    
    Using the account-level data from match_records and calculate_differences:
    1. Extract total NBIM and Custody share positions from previous analysis
    2. Check for exact matches in NOMINAL_BASIS fields
    3. For custody data, analyze LOAN_QUANTITY and HOLDING_QUANTITY fields:
       - Verify: HOLDING_QUANTITY + LOAN_QUANTITY = total custody position
       - Calculate lending percentage: LOAN_QUANTITY / total position × 100
    4. Identify account-level position mismatches (especially Nestle)
    
    Position validation rules based on CSV data:
    - MATCH: NBIM NOMINAL_BASIS = Custody NOMINAL_BASIS (total)
    - MATCH WITH LENDING: Positions match but lending affects dividend treatment
    - CRITICAL MISMATCH: Position differences not explained by lending
    
    Special Focus:
    - Multi-account events: Check individual account positions for discrepancies
    - Events with lending: Verify lending activity impact on positions
    - Single account events: Confirm straightforward position matches
    
    Output format:
    "[Event Key] Position Validation:
    - NBIM Total: [total NOMINAL_BASIS] shares
    - Custody Total: [total NOMINAL_BASIS] shares
    - Account Breakdown: [list individual accounts if multi-account]
    - Lending Activity: [LOAN_QUANTITY] shares ([percentage]%) on loan
    - Status: MATCH/CRITICAL MISMATCH
    - Impact: [description of dividend treatment impact]"
  expected_output: "Position validation using CSV-based account analysis"
  agent: position_validator

analyze_tax_rates:
  description: |
    Compare tax rates using the parsed CSV data from previous tasks.
    
    Using data from match_records and calculate_differences:
    1. Extract NBIM tax rates from WTHTAX_RATE and LOCALTAX_COST_QUOTATION fields
    2. Extract Custody tax rates from TAX_RATE field
    3. Note: NBIM may have split tax structure (withholding + local)
    4. Calculate rate differences and financial impact
    
    Tax Analysis Focus:
    - Identify withholding vs treaty rate differences >1%
    - Check for treaty optimization opportunities  
    - Consider local tax components in NBIM data vs single rates in custody data
    
    Tax Analysis Process:
    - Calculate total NBIM tax rate: (WTHTAX_COST_QUOTATION + LOCALTAX_COST_QUOTATION) / GROSS_AMOUNT_QUOTATION × 100
    - Compare with Custody TAX_RATE
    - Calculate financial impact: gross_amount × (rate_difference / 100)
    
    Output format:
    "[Event Key] Tax Analysis:
    - NBIM Rate: [total_tax_rate]% (WHT: [WTHTAX_RATE]% + Local: [local_rate]%)
    - Custody Rate: [TAX_RATE]%
    - Rate Difference: [calculated_diff]%
    - Financial Impact: [amount] [currency] potential savings/cost
    - Treaty Opportunity: YES/NO (>1% difference threshold)
    - Recommendation: [specific action based on analysis]"
  expected_output: "Tax rate comparison using CSV data with treaty optimization analysis"
  agent: tax_analyst

check_securities_lending:
  description: |
    Analyze securities lending impact using CSV data from previous tasks.
    
    Using data from match_records analysis:
    1. Extract LOAN_QUANTITY and HOLDING_QUANTITY from custody CSV data
    2. Calculate lending percentages and treaty impact
    3. Focus on identifying lending activity (any events with LOAN_QUANTITY > 0)
    4. Analyze tax efficiency implications
    
    Lending Analysis Process:
    - Check custody LOAN_QUANTITY field for each account
    - Calculate total lending: sum of all LOAN_QUANTITY values
    - Verify equation: HOLDING_QUANTITY + LOAN_QUANTITY = NOMINAL_BASIS
    - Calculate lending percentage: LOAN_QUANTITY / NOMINAL_BASIS × 100
    
    Tax efficiency impact assessment:
    - Extract dividend per share from DIVIDENDS_PER_SHARE (NBIM)
    - Calculate potential tax cost of lending based on rate differences
    - Estimate foregone treaty benefits
    
    Tax efficiency impact levels:
    - OPTIMAL: No lending (0%)
    - LOW: <5% on loan
    - MEDIUM: 5-10% on loan
    - HIGH: >10% on loan
    
    Output format:
    "[Event Key] Lending Analysis:
    - Total Position: [NOMINAL_BASIS] shares
    - Shares on loan: [LOAN_QUANTITY] ([lending_percentage]%)
    - Shares with treaty benefits: [HOLDING_QUANTITY] ([effective_coverage]%)
    - Tax efficiency impact: [OPTIMAL/LOW/MEDIUM/HIGH]
    - Estimated treaty cost: [calculation if applicable] [currency]
    - Recommendation: [lending strategy advice]"
  expected_output: "Securities lending impact analysis using CSV lending data"
  agent: securities_lending_checker

validate_fx_rates:
  description: |
    Validate FX rates and currency handling using CSV data from previous tasks.
    
    CRITICAL: Understand the FX rate fields correctly:
    - NBIM's AVG_FX_RATE_QUOTATION_TO_PORTFOLIO: Conversion rate from quotation currency to NOK (portfolio base currency)
    - Custody's FX_RATE: Conversion rate for settlement currency conversion (if applicable)
    - These are DIFFERENT rates serving different purposes - DO NOT compare them directly
    
    Using currency data from match_records analysis:
    1. Extract QUOTATION_CURRENCY and SETTLEMENT_CURRENCY from NBIM data
    2. Extract CURRENCIES and SETTLED_CURRENCY from custody data
    3. Analyze NBIM's AVG_FX_RATE_QUOTATION_TO_PORTFOLIO (quotation → NOK rate for portfolio reporting)
    4. Analyze Custody's FX_RATE (operational rate for currency conversion if cross-currency)
    5. Check IS_CROSS_CURRENCY_REVERSAL flag for complex conversions
    
    FX Analysis approach:
    - For NBIM: AVG_FX_RATE_QUOTATION_TO_PORTFOLIO is ALWAYS the rate to NOK, regardless of settlement currency
      * This rate converts dividend amounts to NOK for portfolio-level reporting
      * Rate magnitude depends on relative strength of quotation currency vs NOK
      * DO NOT flag rates >1 or <1 as errors - they reflect actual currency relationships
    - For Custody: FX_RATE applies only when CURRENCIES ≠ SETTLED_CURRENCY
      * Single currency events: FX_RATE should be 1.0
      * Cross-currency events: FX_RATE = actual conversion rate used for settlement
    
    Validation focus:
    - DO NOT compare NBIM's portfolio reporting rate (to NOK) with Custody's settlement rate
    - Verify settlement amount consistency within each system
    - Check if cross-currency conversions are handled properly
    - Validate that settlement currencies align between systems
    
    Output format:
    "[Event Key] FX Analysis:
    - NBIM Portfolio Reporting: [QUOTATION_CURRENCY] → NOK (Rate: [AVG_FX_RATE_QUOTATION_TO_PORTFOLIO])
    - NBIM Settlement: [QUOTATION_CURRENCY] → [SETTLEMENT_CURRENCY]
    - Custody Processing: [CURRENCIES] → [SETTLED_CURRENCY] (Rate: [FX_RATE])
    - Cross-currency reversal: [IS_CROSS_CURRENCY_REVERSAL]
    - Settlement consistency: [Verify settlement amounts match within each system]
    - Analysis: [Focus on settlement currency alignment and conversion methodology]"
  expected_output: "FX rate validation using CSV currency data"
  agent: fx_validator

assess_risk:
  description: |
    Prioritize findings using data from all previous CSV-based analyses.
    
    Using consolidated findings from:
    - calculate_differences: Amount discrepancies and percentages
    - validate_positions: Share position issues
    - analyze_tax_rates: Tax optimization opportunities
    - check_securities_lending: Lending impact assessment
    - validate_fx_rates: Currency handling issues
    
    Risk assessment criteria based on CSV analysis:
    1. Financial materiality: Currency amounts and percentages from calculations
    2. Position integrity: Share mismatches from position validation
    3. Operational impact: Date discrepancies, lending effects, FX issues
    4. Tax efficiency: Treaty optimization potential
    
    Priority levels based on CSV findings:
    - CRITICAL: Position differences, major date discrepancies (>5 days)
    - HIGH: >5% amount differences, significant tax rate differences (>2%)
    - MEDIUM: 2-5% differences, moderate lending impact (5-10%)
    - LOW: <2% differences, minimal operational impact
    - PERFECT: All measures within acceptable tolerance
    
    Priority Classification Guidelines:
    - Events with position differences: CRITICAL priority
    - Events with significant tax rate differences (>2%): HIGH priority
    - Events with lending activity affecting tax efficiency: HIGH priority
    - Events with perfect matches across all metrics: PERFECT priority
    
    Output format:
    "[Event Key] Priority: [LEVEL]
    Drivers: [Specific findings that drove this priority]
    - Financial Impact: [amount differences and percentages]
    - Position Issues: [share differences]
    - Operational Issues: [dates, lending, FX]
    - Tax Optimization: [treaty opportunities]
    Action required: [immediate/planned/monitoring with timeline]"
  expected_output: "Risk prioritization based on comprehensive CSV analysis findings"
  agent: risk_prioritizer

write_report:
  description: |
    Create comprehensive executive report synthesizing all CSV-based analysis findings.
    
    Consolidate findings from all previous tasks:
    - match_records: Event matching and account details
    - calculate_differences: Amount discrepancies in original currencies
    - validate_positions: Share position validation
    - analyze_tax_rates: Tax optimization opportunities
    - check_securities_lending: Lending impact analysis
    - validate_fx_rates: Currency handling validation
    - assess_risk: Priority classification
    
    REQUIRED REPORT STRUCTURE:
    
    # EXECUTIVE SUMMARY
    - Total dividend events analyzed: [count from CSV parsing]
    - Perfect matches: [events with no discrepancies]
    - Events with discrepancies: [events requiring attention]
    - Critical issues requiring immediate action: [count]
    
    # DETAILED FINDINGS
    For each event, synthesize from all analyses:
    "**[Event Key] Company: [ORGANISATION_NAME]**
    - Currency: [original currency preserved]
    - Amounts: NBIM vs Custody differences with percentages
    - Positions: Share reconciliation status
    - Dates: Payment/ex-date validation results
    - Tax Analysis: Rate differences and treaty opportunities
    - Securities Lending: Impact on tax efficiency
    - FX Rates: Currency handling validation
    - Risk Priority: [from risk assessment]
    - Account Details: [if multi-account event]"
    
    # FINANCIAL IMPACT SUMMARY
    - Material discrepancies by currency
    - Tax optimization potential
    - Securities lending cost analysis
    
    # CRITICAL ISSUES
    List all CRITICAL priority items with:
    - Root cause analysis
    - Financial impact
    - Required actions
    
    # ACTIONABLE RECOMMENDATIONS
    Prioritized action items with timelines and ownership.
    
    IMPORTANT: Preserve original currencies throughout report. Synthesize from all task outputs.
  expected_output: "Comprehensive executive report based on complete CSV analysis"
  agent: report_writer